#!/usr/bin/env bash
# =============================================================
# setup.sh — Run once after cloning. Detects hardware, builds
#             the Docker image, and writes config for run.sh.
#
# Usage:
#   ./setup.sh          # auto-detect CPU vs GPU
#   ./setup.sh --cpu    # force CPU even if GPU is present
#   ./setup.sh --gpu    # force GPU (will fail if no GPU)
# =============================================================
set -euo pipefail

FORCE=""
while [[ $# -gt 0 ]]; do
    case "$1" in
        --cpu) FORCE=cpu; shift ;;
        --gpu) FORCE=gpu; shift ;;
        *)     echo "Unknown option: $1"; exit 1 ;;
    esac
done

# ── 1. Check Docker ──────────────────────────────────────────
echo "Checking Docker..."
if ! command -v docker &>/dev/null; then
    echo "ERROR: docker is not installed."
    echo "Install it: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &>/dev/null; then
    echo "ERROR: 'docker compose' plugin not found."
    echo "Install it: https://docs.docker.com/compose/install/"
    exit 1
fi
echo "  Docker $(docker --version | grep -oP '\d+\.\d+\.\d+') — OK"

# ── 2. Detect GPU ────────────────────────────────────────────
DEVICE=cpu

if [[ "$FORCE" == "cpu" ]]; then
    DEVICE=cpu
    echo "  Forced CPU mode."
elif [[ "$FORCE" == "gpu" ]]; then
    DEVICE=gpu
    echo "  Forced GPU mode."
else
    if command -v nvidia-smi &>/dev/null && nvidia-smi &>/dev/null; then
        GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
        echo "  NVIDIA GPU detected: $GPU_NAME"
        DEVICE=gpu
    else
        echo "  No NVIDIA GPU detected — using CPU."
    fi
fi

# ── 3. If GPU, check nvidia-container-toolkit ────────────────
if [[ "$DEVICE" == "gpu" ]]; then
    if docker info 2>/dev/null | grep -q "nvidia"; then
        echo "  nvidia-container-toolkit — OK"
    else
        echo ""
        echo "WARNING: nvidia-container-toolkit does not appear to be configured."
        echo "GPU passthrough will not work without it."
        echo ""
        echo "Install guide:"
        echo "  https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
        echo ""
        read -rp "Continue with CPU instead? [Y/n] " yn
        case "${yn,,}" in
            n|no) echo "Aborting."; exit 1 ;;
            *)    DEVICE=cpu; echo "  Falling back to CPU." ;;
        esac
    fi
fi

# ── 4. Write docker-compose.override.yml (GPU only) ─────────
OVERRIDE="docker-compose.override.yml"

if [[ "$DEVICE" == "gpu" ]]; then
    echo "  Writing $OVERRIDE for GPU..."
    cat > "$OVERRIDE" <<'EOF'
# Auto-generated by setup.sh — do not edit manually.
# Delete this file to revert to CPU: rm docker-compose.override.yml
services:
  experiment:
    build:
      args:
        DEVICE: gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  visualize:
    build:
      args:
        DEVICE: gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
EOF
else
    # Remove stale override from a previous GPU setup
    rm -f "$OVERRIDE"
fi

# ── 5. Build the image ───────────────────────────────────────
echo ""
echo "Building Docker image (DEVICE=$DEVICE)..."
docker compose build

# ── 6. Done ──────────────────────────────────────────────────
echo ""
echo "============================================="
echo "  Setup complete!  (device: $DEVICE)"
echo "============================================="
echo ""
echo "Run an experiment:"
echo "  N_EXPERIMENT=1 ./run.sh"
echo ""
echo "Or with custom parameters:"
echo "  N_EXPERIMENT=5 N_EPOCHS=100 LATENT_DIM=128 ./run.sh"
echo ""
echo "Run all 45 experiments:"
echo "  for i in \$(seq 1 45); do N_EXPERIMENT=\$i ./run.sh; done"
